blank_issues_enabled: false

contact_links:
  - name: Contributing Guide
    url: https://github.com/mcflugen/gimli/blob/main/CONTRIBUTING.md
    about: Please review contribution guidelines before submitting a PR.

  - name: Documentation
    url: https://github.com/mcflugen/gimli/blob/main/README.md
    about: Check the documentation before opening a PR.
