name: PyPI

on: [push]

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: true

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Install requirements
        run: |
          conda install mamba
          mamba install --file=requirements.txt udunits2
          mamba list

      - name: Install pypa/build
        run: |
          pip install twine wheel cython
          python setup.py bdist_wheel
          twine upload --skip-existing -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} dist/*gimli* --repository-url=https://test.pypi.org/legacy/
